import {
  ComparativeSection,
  Footer,
  Header,
  Message,
  VideosSection
} from '@/components'
import { LoadingScreen } from '@/components/LoadingScreen';
import Head from 'next/head'
import { useEffect, useState } from 'react';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 3000);
  }, []);

  return (
    <>
      <Head>
        <title>Leadster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? <LoadingScreen /> : (
        <>
          <Header />
          <Message />
          <VideosSection />
          <ComparativeSection />
          <Footer />
        </>
      )}
    </>
  )
}
